services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: botai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    volumes:
      - db-data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      network: host
    network_mode: host
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_DATABASE: botai

      WOW_CLIENT_ID:     ${WOW_CLIENT_ID}
      WOW_CLIENT_SECRET: ${WOW_CLIENT_SECRET}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DEVELOPMENT_GUILD_ID: ${DEVELOPMENT_GUILD_ID}
      OPENAI_API_KEY:    ${OPENAI_API_KEY}
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

volumes:
  db-data:
